Database:           # Database configuration
  URI:                mongodb://localhost:27017   # MongoDB URI
  db:                 Shaft                       # Database name
  collection:       # Collection configuration
    back:             BACKUP                      # Backup collection name
    raw:              RAW                         # Raw data collection name
    unconsumed:       UNCONSUMED                  # Unconsumed data collection name
    healthy:          HEALTHY                     # Healthy data collection name
    healthy_train:    HEALTHY_TRAIN               # Healthy data collection name for training (some healthy data are not used if not novelty)
    quarantined:      QUARANTINED                 # Quarantined data collection name
    faulty:           FAULTY                      # Faulty data collection name
    faulty_train:     FAULTY_TRAIN                # Faulty data collection name for training (some faulty data are not used if not fault novelty)
    models:           MODELS                      # Models collection name
  sensors:          # Expected sensors in the database
    # Bearing 1 x:    # Sensor 1 name
    #   features:     # Features configuration
    #     wavPowers:    on                          # Wavelet powers
    #     mean:         on                          # Mean value
    #     rms:          on                          # Root mean square
    #     peak:         on                          # Peak to peak value
    #     std:          on                          # Standard deviation
    #     skew:         on                          # Skewness
    #     kurt:         on                          # Kurtosis
    # Bearing 1 y:    # Sensor 2 name
    #   features:     # Features configuration
    #     wavPowers:    on                          # Wavelet powers
    #     mean:         on                          # Mean value
    #     rms:          on                          # Root mean square
    #     peak:         on                          # Peak to peak value
    #     std:          on                          # Standard deviation
    #     skew:         on                          # Skewness
    #     kurt:         on                          # Kurtosis
    # Bearing 2 x:    # Sensor 3 name
    #   features:     # Features configuration
    #     wavPowers:    on                          # Wavelet powers
    #     mean:         on                          # Mean value
    #     rms:          on                          # Root mean square
    #     peak:         on                          # Peak to peak value
    #     std:          on                          # Standard deviation
    #     skew:         on                          # Skewness
    #     kurt:         on                          # Kurtosis
    # Bearing 2 y:    # Sensor 3 name
    #   features:     # Features configuration
    #     wavPowers:    on                          # Wavelet powers
    #     mean:         on                          # Mean value
    #     rms:          on                          # Root mean square
    #     peak:         on                          # Peak to peak value
    #     std:          on                          # Standard deviation
    #     skew:         on                          # Skewness
    #     kurt:         on                          # Kurtosis
    Bearing 3 x:    # Sensor 3 name
      features:     # Features configuration
        wavPowers:    on                          # Wavelet powers
        mean:         on                          # Mean value
        rms:          on                          # Root mean square
        peak:         on                          # Peak to peak value
        std:          on                          # Standard deviation
        skew:         on                          # Skewness
        kurt:         on                          # Kurtosis
    # Bearing 3 y:    # Sensor 3 name
    #   features:     # Features configuration
    #     wavPowers:    on                          # Wavelet powers
    #     mean:         on                          # Mean value
    #     rms:          on                          # Root mean square
    #     peak:         on                          # Peak to peak value
    #     std:          on                          # Standard deviation
    #     skew:         on                          # Skewness
    #     kurt:         on                          # Kurtosis
    # Bearing 4 x:    # Sensor 3 name
    #   features:     # Features configuration
    #     wavPowers:    on                          # Wavelet powers
    #     mean:         on                          # Mean value
    #     rms:          on                          # Root mean square
    #     peak:         on                          # Peak to peak value
    #     std:          on                          # Standard deviation
    #     skew:         on                          # Skewness
    #     kurt:         on                          # Kurtosis
    # Bearing 4 y:    # Sensor 3 name
    #   features:     # Features configuration
    #     wavPowers:    on                          # Wavelet powers
    #     mean:         on                          # Mean value
    #     rms:          on                          # Root mean square
    #     peak:         on                          # Peak to peak value
    #     std:          on                          # Standard deviation
    #     skew:         on                          # Skewness
    #     kurt:         on                          # Kurtosis
wavelet:           # Wavelet packet reasform configuration
  type:               db10                        # Type of wavelet to use
  mode:               symmetric                   # Mode of the packet transform
  maxlevel:           6                           # Max level -> num of features = 2^level
kmeans:            # kmean configuration
  max_clusters:       100                         # Max number of clusters
  max_iterations:     1000                        # Max number of iterations
  error_queue_size:   1                           # number of predictions parameters to keep in quewe for plotting/predicting
  error_plot_size:    2000                        # Size of the plotting queue

novelty:           # Novelty/fault configuration
  threshold:          0.10                        # Threshold for novelty / fault detection:
#                                                   relative percentage of the distance to the cluster w.r.t the max distance
#                                                   to the assigned cluster in the training set
  forecast_threshold: 0.8                         # Threshold for novelty / fault prediction
  n_fit:              250                         # Number of samples used to fit the prediction curve
  outlier_filter:     1                           # Number of consecutive outliers to filter (1 means two outliers will be considered as novelty/fault)
  regressor:          exp                         # Regressor to use for prediction: exp, scipy, poly. if exp uses custom function, if scipy uses scipy.optimize.curve_fit, if poly fit polinomial of degree

miscellanea:
  logpath:            C:\Users\ariel\Documents\Courses\Tesi\Code\framework        # Path to the logs