Database:           # Database configuration
  URI:                mongodb://localhost:27017   # MongoDB URI
  db:                 Shaft                       # Database name
  collection:       # Collection configuration
    back:             BACKUP                      # Backup collection name
    raw:              RAW                         # Raw data collection name
    unconsumed:       UNCONSUMED                  # Unconsumed data collection name
    healthy:          HEALTHY                     # Healthy data collection name
    quarantined:      QUARANTINED                 # Quarantined data collection name
    faulty:           FAULTY                      # Faulty data collection name
    models:           MODELS                      # Models collection name
  sensors:          # Expected sensors in the database
    Bearing 1 x:    # Sensor 1 name
      features:     # Features configuration
        wavPowers:    on                          # Wavelet powers
        mean:         on                          # Mean value
        rms:          on                          # Root mean square
        peak:         on                          # Peak to peak value
        std:          on                          # Standard deviation
    Bearing 1 y:    # Sensor 2 name
      features:     # Features configuration
        wavPowers:    on                          # Wavelet powers
        mean:         on                         # Mean value
        rms:          off                         # Root mean square
        peak:         off                         # Peak to peak value
        std:          off                         # Standard deviation
    Bearing 2 x:    # Sensor 3 name
      features:     # Features configuration
        wavPowers:    off                         # Wavelet powers
        mean:         on                          # Mean value
        rms:          off                         # Root mean square
        peak:         off                         # Peak to peak value
        std:          on                          # Standard deviation
wavelet:           # Wavelet packet reasform configuration
  type:               db10                        # Type of wavelet to use
  mode:               symmetric                   # Mode of the packet transform
  maxlevel:           6                           # Max level -> num of features = 2^level
kmeans:            # kmean configuration
  max_clusters:       100                         # Max number of clusters
MLA:               # machine learning agent settings
  mode:               train                       # Mode of the agent (evaluate, train, retrain)
